# Generated by Django 4.1.3 on 2022-12-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=20)),
                ('First_name', models.CharField(max_length=20)),
                ('Middle_name', models.CharField(max_length=20)),
                ('st_name', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=40)),
                ('Phone_No', models.IntegerField()),
                ('Admin', models.BooleanField(default=False)),
            ],
        ),
    ]
