# Generated by Django 4.1.3 on 2022-12-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='st_name',
            new_name='Last_name',
        ),
    ]
