# Generated by Django 4.1.3 on 2023-01-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0002_rename_st_name_users_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.DateField()),
                ('TimeSlot', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=20)),
                ('P_med', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
                ('Content', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=20)),
                ('Img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='H_remedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Desc', models.CharField(max_length=20)),
                ('Accessories', models.CharField(max_length=20)),
                ('Img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='M_remedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Desc', models.CharField(max_length=20)),
                ('Content', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Img', models.ImageField(upload_to='')),
            ],
        ),
    ]
