# Generated by Django 4.1.3 on 2023-01-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0003_appointments_blogs_h_remedy_m_remedy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Password',
        ),
        migrations.AddField(
            model_name='users',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='Gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='Img',
            field=models.ImageField(blank=True, default='Prakruti_App/Users_images/user1.jpg', null=True, upload_to='Prakruti_App/Users_images/'),
        ),
        migrations.AddField(
            model_name='users',
            name='P_Prakruti',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='users',
            name='S_Prakruti',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='P_med',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='TimeSlot',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Content',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Img',
            field=models.ImageField(blank=True, default='Prakruti_App/blogs_images/blog1.jpg', null=True, upload_to='Prakruti_App/blogs_images/'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='text',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='h_remedy',
            name='Accessories',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='h_remedy',
            name='Desc',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='h_remedy',
            name='Img',
            field=models.ImageField(blank=True, default='Prakruti_App/Hom_images/hr1.jpg', null=True, upload_to='Prakruti_App/Hom_images/'),
        ),
        migrations.AlterField(
            model_name='h_remedy',
            name='Name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='m_remedy',
            name='Content',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='m_remedy',
            name='Desc',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='m_remedy',
            name='Img',
            field=models.ImageField(blank=True, default='Prakruti_App/Med_images/mr1.jpg', null=True, upload_to='Prakruti_App/Med_images/'),
        ),
        migrations.AlterField(
            model_name='m_remedy',
            name='Name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='Middle_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='Phone_No',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='UserName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
