# Generated by Django 4.1.3 on 2023-01-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0004_remove_users_admin_remove_users_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Phone_No',
            field=models.BigIntegerField(default=0),
        ),
    ]
