# Generated by Django 4.1.3 on 2023-01-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0006_med_per_ord_orders_rename_day_appointments_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='U_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='m_remedy',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='m_remedy',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='med_per_ord',
            name='m_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='med_per_ord',
            name='o_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='o_id',
            field=models.IntegerField(default=0),
        ),
    ]
