# Generated by Django 4.1.3 on 2023-01-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0007_alter_appointments_u_id_alter_m_remedy_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='Status',
        ),
        migrations.AddField(
            model_name='appointments',
            name='Status_A',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointments',
            name='Status_R',
            field=models.BooleanField(default=False),
        ),
    ]
