# Generated by Django 4.1.3 on 2023-01-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0008_remove_appointments_status_appointments_status_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='P_med',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
