# Generated by Django 4.1.3 on 2023-01-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0009_alter_appointments_p_med'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='id',
        ),
        migrations.AlterField(
            model_name='orders',
            name='o_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
