# Generated by Django 4.1.3 on 2023-02-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0010_remove_orders_id_alter_orders_o_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='h_remedy',
            name='Accessories',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='h_remedy',
            name='Desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='m_remedy',
            name='Content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='m_remedy',
            name='Desc',
            field=models.TextField(default=''),
        ),
    ]
