# Generated by Django 4.1.3 on 2023-02-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0011_alter_blogs_content_alter_h_remedy_accessories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
