# Generated by Django 4.1.3 on 2023-02-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0012_blogs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='med_per_ord',
            name='m_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
