# Generated by Django 4.1.3 on 2023-02-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0013_med_per_ord_m_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med_per_ord',
            name='m_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
