# Generated by Django 4.1.3 on 2023-02-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0014_alter_med_per_ord_m_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='P_med',
            field=models.TextField(default=''),
        ),
    ]
