# Generated by Django 4.1.4 on 2023-02-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0014_alter_med_per_ord_m_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=20)),
                ('p_id', models.IntegerField(default=0)),
            ],
        ),
    ]
