# Generated by Django 4.1.3 on 2023-02-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0015_cart'),
        ('Prakruti_App', '0016_prakruti_quetions_alter_appointments_date'),
    ]

    operations = [
    ]
