# Generated by Django 4.1.3 on 2023-02-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0018_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prakruti_Quetions',
        ),
    ]
