# Generated by Django 4.1.3 on 2023-06-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0021_complaint_quetions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prakruti_Quetions_Ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField(default=0)),
                ('age', models.TextField(default='')),
                ('ans1', models.TextField(default='')),
                ('ans2', models.TextField(default='')),
                ('ans3', models.TextField(default='')),
                ('ans4', models.TextField(default='')),
                ('ans5', models.TextField(default='')),
                ('ans6', models.TextField(default='')),
                ('ans7', models.TextField(default='')),
                ('ans8', models.TextField(default='')),
                ('ans9', models.TextField(default='')),
                ('ans10', models.TextField(default='')),
                ('ans11', models.TextField(default='')),
                ('ans12', models.TextField(default='')),
                ('ans13', models.TextField(default='')),
                ('ans14', models.TextField(default='')),
                ('ans15', models.TextField(default='')),
                ('ans16', models.TextField(default='')),
                ('ans17', models.TextField(default='')),
                ('ans18', models.TextField(default='')),
                ('ans19', models.TextField(default='')),
                ('ans20', models.TextField(default='')),
                ('ans21', models.TextField(default='')),
                ('ans22', models.TextField(default='')),
                ('ans23', models.TextField(default='')),
            ],
        ),
    ]
