# Generated by Django 4.1.4 on 2023-06-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0022_prakruti_quetions_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_remedy',
            name='Category',
            field=models.TextField(default=''),
        ),
    ]
