# Generated by Django 4.1.4 on 2023-06-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0023_m_remedy_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med_per_ord',
            old_name='m_name',
            new_name='U_name',
        ),
    ]
