# Generated by Django 4.1.4 on 2023-06-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0024_rename_m_name_med_per_ord_u_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med_per_ord',
            name='o_id',
            field=models.IntegerField(default=0,serialize=False),
        ),
    ]
