# Generated by Django 4.1.4 on 2023-06-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0025_med_per_ord_m_qt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Address',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='med_per_ord',
            name='o_id',
            field=models.IntegerField(default=0),
        ),
    ]
