# Generated by Django 4.1.4 on 2023-06-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0026_orders_address_alter_med_per_ord_o_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
