# Generated by Django 4.1.3 on 2023-10-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prakruti_App', '0027_med_per_ord_m_qt_orders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='med_per_ord',
            name='m_qt',
            field=models.IntegerField(default=0),
        ),
    ]
